org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true

# Veil environment (override in local.properties or CI)
veil.relay.baseUrl=http://10.0.2.2:8080
veil.useMockServices=true

kotlin.mpp.androidGradlePluginCompatibility.nowarn=true
kotlin.native.ignoreDisabledTargets=true
